### PR TITLE
feat(intl-tel-input): update to 14.0.3 

### PR DESCRIPTION
**Pull request by leo6104**
Related Issue: 
https://github.com/gauravsoni119/ng2-tel-input/issues/22

Recently, intl-tel-input release 14.0.3 and it remove jquery dependency. 

Also, it support server side rendering with isPlatformBrowser check logic.

### CODE REVIEW

**Comment by PACMAN49** [comment]
any chance to see this PR merged ?

**Comment by najibla** [comment]
Merge please!

**Comment by rovercoder** [comment]
Would like to see this merged!

**Comment by leo6104** [comment]
@PACMAN49 @najibla @rovercoder 
You can use my commit version with this command.
`npm install --save https://github.com/leo6104/ng2-tel-input.git#dist`

**Comment by mmestani** [comment]
@leo6104 it seems this version doesn't fill the `dialCode` on focus in the input when `nationalMode: false`

**Comment by songokudbz** [comment]
Pls merge.

**Comment by gauravsoni119** [comment]
Sorry for the very long delay. I am quite busy with other projects. Thanks for the pull request.

**Pull request merged**
