### PR TITLE
Upgarde peerDependency to 5.2.3 to be able to work in Angular 5 app.

### PR DESCRIPTION
**Pull request by chaabenMohamed**
this commit is needed to Fix this bug: Uncaught Error: Unexpected value 'Ng2TelInputModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

### CODE REVIEW

**Comment by gauravsoni119** [comment]
Hi @chaabenMohamed , Firstly thanks for this pull request. I tried your code on my local. I got some errors. I attached an image of errors. Have you get these errors? I think these errors are related to types of jquery. I am trying to fix these. 

error_pull_request

**Comment by chaabenMohamed** [comment]
Hello @gauravsoni119, for me I have another error:
screenshot from 2018-03-19 15-29-38

**Comment by chaabenMohamed** [comment]
After removing jquery and @angular/core from dependencies, every thing work well,
I think in your error you should just remove jquery from dependecies

**Comment by gauravsoni119** [comment]
Hi @chaabenMohamed, I fixed the issue and pushed it. The issue is also related to code.

**Comment by chaabenMohamed** [comment]
Hier @gauravsoni119, good work, but I think it's best tout use keyup instead if using Blur event, to Can checkbox wrong phone number un Real Time.

**Pull request closed without merging**
